spring:
  cloud:
    gateway:
      routes:
        - id: api-service-candidatos
          uri: lb://api-service-candidatos
          predicates:
            - Path=/api/v1/candidatos/**
          filters:
            - StripPrefix=3
        - id: api-service-documentos
          uri: lb://api-service-documentos
          predicates:
            - Path=/api/v1/documentos/**
          filters:
            - StripPrefix=3
